In [1]:
import pandas as pd
import statsmodels.api as sm
import statsmodels.formula.api as smf
import numpy as np

In [2]:
# Load your data
posts = pd.read_csv("/Users/pouriakhansari/Library/CloudStorage/OneDrive-IveyBusinessSchool/Prashant/Content Format/Code/EnsembleData/Instagram/ig_post_info.csv")

posts.head()

,brand,ig_brand_ID,brand_Username,post_id,product_type,post_type,timestamp,scrape_ts,page,cover_url,...,mentions,co_creators,is_paid_partnership,is_affiliate,sponsored_partnership,location,has_upcoming_event,product_tags,_raw_file,_user_id
0,Google,69550579620,googlegemini,3835422615627999905,clips,GraphVideo,1771438053,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,NaN,google,False,False,NaN,NaN,False,NaN,google_20260218_151943_page1.json,1067259270
1,Google,1067259270,google,3835405492215196230,clips,GraphVideo,1771436226,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,False,False,NaN,NaN,False,NaN,google_20260218_151943_page1.json,1067259270
2,Google,69550579620,googlegemini,3835391197422670634,NaN,GraphSidecar,1771434281,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,NaN,google,False,False,NaN,NaN,False,NaN,google_20260218_151943_page1.json,1067259270
3,Google,11421759503,googlefordevs,3834753934065553649,clips,GraphVideo,1771358470,1771445983,1,https://instagram.fbkk7-3.fna.fbcdn.net/v/t51....,...,NaN,"googlegemini, google, googledeepmind",False,False,NaN,NaN,False,NaN,google_20260218_151943_page1.json,1067259270
4,Google,1067259270,google,3834664334044237488,NaN,GraphSidecar,1771347632,1771445983,1,https://instagram.fbkk7-3.fna.fbcdn.net/v/t51....,...,NaN,NaN,False,False,NaN,NaN,False,NaN,google_20260218_151943_page1.json,1067259270

In [3]:
user=pd.read_csv("/Users/pouriakhansari/Library/CloudStorage/OneDrive-IveyBusinessSchool/Prashant/Content Format/Code/EnsembleData/Instagram/ig_user_info.csv")
user

,brand,username,user_id,fbid,fb_profile_biolink,category_name,is_verified,is_business_account,is_professional_account,biography,...,profile_pic_url_hd,is_private_detailed,business_type,business_email,city_name,city_id,latitude,longitude,street_address,zip_code
0,Allianz,allianz,2.140366e+08,1.784140e+16,NaN,NaN,True,True,True,Insuring the world for 135 years. #StepIntoLife,...,https://instagram.fhmo2-4.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Amazon Web Services,amazonwebservices,1.437392e+09,1.784140e+16,NaN,NaN,True,True,True,Amazon Web Services (AWS),...,https://scontent-ham3-1.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Aramco,aramco,1.815950e+09,1.784140e+16,NaN,NaN,True,True,True,where energy is opportunity,...,https://scontent-mia5-1.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Budweiser,budweiser,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Coca-Cola,cocacola,2.496552e+08,1.784140e+16,NaN,NaN,True,True,True,Classic since always.,...,https://instagram.fktp2-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Deloitte,deloitte,2.866331e+06,1.784140e+16,NaN,NaN,True,True,True,"At Deloitte, we make an impact that matters.",...,https://instagram.fruh4-6.fna.fbcdn.net/v/t51....,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Deutsche Telekom,deutschetelekom,2.160232e+09,1.784140e+16,NaN,NaN,True,True,True,"Content wie unser Netz: schnell, stabil, Magen...",...,https://scontent-fco2-1.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Google,google,1.067259e+09,1.784140e+16,NaN,Internet company,True,True,True,Here to help,...,https://instagram.fksc2-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Google,googlepixel,8.482989e+09,1.784141e+16,NaN,Community Organization,True,True,True,A perfect 10 📱,...,https://instagram.fhyd11-2.fna.fbcdn.net/v/t51...,False,B2C,NaN,"Mountain View, California",1.082126e+14,37.389670,-122.081610,NaN,NaN
9,Google,madebygoogle,4.512855e+09,1.784140e+16,NaN,NaN,True,True,True,"Designed for your everyday.\n#Pixel10, 10 Pro,...",...,https://scontent-nrt1-2.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Instagram,instagram,2.502532e+07,1.784140e+16,NaN,NaN,True,False,True,Watch the latest episode of Close Friends Only,...,https://instagram.fcdg1-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,J.P. Morgan,jpmorganprivatebank,4.880823e+10,1.784145e+16,NaN,Financial service,True,True,True,Join us for a view into the elevated experienc...,...,https://scontent-iad3-2.cdninstagram.com/v/t51...,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Loreal,lorealparis,1.323767e+09,1.784140e+16,NaN,NaN,True,True,True,Because we are all worth it.\nShow us your wor...,...,https://instagram.fcdg3-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,McDonald,mcdonalds,1.834315e+07,1.784140e+16,NaN,NaN,True,True,True,grimace is a close personal friend of mine,...,https://instagram.fiev21-2.fna.fbcdn.net/v/t51...,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Microsoft,microsoft,5.245493e+08,1.784140e+16,NaN,NaN,True,True,True,running on iced coffee and deadlines,...,https://instagram.fmcz12-1.fna.fbcdn.net/v/t51...,False,B2C,NaN,"Redmond, Washington",1.097388e+14,47.669400,-122.124000,NaN,NaN
15,Moutai,moutai.china,1.507995e+09,1.784140e+16,NaN,NaN,False,True,True,Welcome to Kweichow Moutai global official Ins...,...,https://scontent-tpe1-1.cdninstagram.com/v/t51...,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NVIDIA,nvidia,1.441656e+09,1.784140e+16,NaN,NaN,True,True,True,NVIDIA pioneered accelerated computing to tack...,...,https://instagram.frns1-1.fna.fbcdn.net/v/t51....,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Shell,shell,5.882827e+08,1.784140e+16,NaN,NaN,True,True,True,Connecting people and energy #PoweringProgress⚡️,...,https://scontent-icn2-1.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Siemens,siemens,6.487661e+08,1.784140e+16,NaN,NaN,True,True,True,"A technology company focused on industry, infr...",...,https://scontent-fra5-1.cdninstagram.com/v/t51...,False,B2B,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Telekom / T-Mobile,tmobile,3.062982e+07,1.784140e+16,NaN,Telecommunication company,True,True,True,It's better over here.,...,https://instagram.fykz2-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,UnitedHealthcare,unitedhealthcare,2.121639e+09,1.784140e+16,NaN,NaN,True,True,True,Helping people live healthier lives,...,https://instagram.fist7-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,"Minnetonka, Minnesota",1.095335e+14,44.932000,-93.461600,NaN,NaN
21,Walmart,walmart,3.913630e+08,1.784140e+16,NaN,NaN,True,True,True,Save money. Live better.,...,https://instagram.fbcn5-2.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,adidas,adidas,2.026976e+07,1.784140e+16,NaN,Product/service,True,True,True,#YouGotThis,...,https://scontent-mia5-1.cdninstagram.com/v/t51...,False,B2C,NaN,Herzogenaurach,1.037228e+14,49.583193,10.909425,Adi-Dassler-Str. 1,91074.0
23,Nike,nike,1.346008e+07,1.784140e+16,NaN,NaN,True,True,True,Just Do It.,...,https://scontent-itm1-1.cdninstagram.com/v/t51...,False,B2C,NaN,"Beaverton, Oregon",1.084106e+14,45.507645,-122.826916,One Bowerman Dr,97005.0
24,BMW,bmw,4.310925e+07,1.784140e+16,NaN,NaN,True,True,True,"The official #BMW account, home of Sheer Drivi...",...,https://scontent-mia5-2.cdninstagram.com/v/t51...,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df = posts.merge(user,left_on='ig_brand_ID',right_on='user_id',how='left'
)
df

,brand_x,ig_brand_ID,brand_Username,post_id,product_type,post_type,timestamp,scrape_ts,page,cover_url,...,profile_pic_url_hd,is_private_detailed,business_type,business_email,city_name,city_id,latitude,longitude,street_address,zip_code
0,Google,69550579620,googlegemini,3835422615627999905,clips,GraphVideo,1771438053,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Google,1067259270,google,3835405492215196230,clips,GraphVideo,1771436226,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,https://instagram.fksc2-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Google,69550579620,googlegemini,3835391197422670634,NaN,GraphSidecar,1771434281,1771445983,1,https://instagram.fbkk7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Google,11421759503,googlefordevs,3834753934065553649,clips,GraphVideo,1771358470,1771445983,1,https://instagram.fbkk7-3.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Google,1067259270,google,3834664334044237488,NaN,GraphSidecar,1771347632,1771445983,1,https://instagram.fbkk7-3.fna.fbcdn.net/v/t51....,...,https://instagram.fksc2-1.fna.fbcdn.net/v/t51....,False,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3102,adidas,9187952,adidasoriginals,3759770351690102423,NaN,GraphSidecar,1762419574,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3103,adidas,9187952,adidasoriginals,3759253690411160868,clips,GraphVideo,1762358437,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3104,adidas,9187952,adidasoriginals,3758651514160681654,clips,GraphVideo,1762286500,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3105,adidas,9187952,adidasoriginals,3758320715410452818,NaN,GraphSidecar,1762246764,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3106,adidas,9187952,adidasoriginals,3757596256710189734,clips,GraphVideo,1762160460,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df = df[(df["post_type"] != "GraphVideo") & (df["video_count"] == 0) ]
df = df[df['likes'] >= 0]
# difference in seconds
df['age_seconds'] = df['timestamp'] - df['scrape_ts']

# convert to days
df['age_days'] = df['age_seconds'] / 86400

df

,brand_x,ig_brand_ID,brand_Username,post_id,product_type,post_type,timestamp,scrape_ts,page,cover_url,...,business_type,business_email,city_name,city_id,latitude,longitude,street_address,zip_code,age_seconds,age_days
5,Google,1067259270,google,3833886396759739422,NaN,GraphSidecar,1771254895,1771445983,1,https://instagram.fbkk7-3.fna.fbcdn.net/v/t51....,...,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-191088,-2.211667
14,Google,1067259270,google,3831025532499216749,NaN,GraphSidecar,1770913853,1771445983,1,https://scontent-atl3-3.cdninstagram.com/v/t51...,...,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-532130,-6.158912
15,Google,1067259270,google,3830356172264771263,NaN,GraphSidecar,1770834059,1771445983,1,https://scontent-atl3-3.cdninstagram.com/v/t51...,...,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-611924,-7.082454
18,Google,1067259270,google,3829065115170411987,NaN,GraphSidecar,1770680153,1771445983,1,https://scontent-atl3-3.cdninstagram.com/v/t51...,...,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-765830,-8.863773
20,Google,1067259270,google,3828162854630028490,NaN,GraphSidecar,1770572595,1771445983,1,https://instagram.frba2-1.fna.fbcdn.net/v/t51....,...,B2C,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-873388,-10.108657
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3095,adidas,9187952,adidasoriginals,3765567817379247379,NaN,GraphSidecar,1763110686,1770049452,2,https://instagram.fpss4-1.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6938766,-80.309792
3096,adidas,9187952,adidasoriginals,3765077966150191056,NaN,GraphSidecar,1763052291,1770049452,2,https://instagram.fpss4-1.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-6997161,-80.985660
3098,adidas,9187952,adidasoriginals,3763606337649945077,NaN,GraphSidecar,1762876859,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7172593,-83.016123
3102,adidas,9187952,adidasoriginals,3759770351690102423,NaN,GraphSidecar,1762419574,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7629878,-88.308773
3105,adidas,9187952,adidasoriginals,3758320715410452818,NaN,GraphSidecar,1762246764,1770049452,2,https://instagram.flwo7-2.fna.fbcdn.net/v/t51....,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-7802688,-90.308889

In [6]:
df_m = df[['likes', 'media_count','comments','post_type','brand_x','followers','age_days', 'business_type']].copy()
df_m['log_followers'] = np.log(df_m['followers'])

df_m = df_m.dropna()

In [8]:
model = smf.glm(
    'likes ~ C(post_type) + C(business_type) + log_followers + age_days',
    data=df_m,
    family=sm.families.NegativeBinomial()
).fit()


print(model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  likes   No. Observations:                 1316
Model:                            GLM   Df Residuals:                     1311
Model Family:        NegativeBinomial   Df Model:                            4
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -12933.
Date:                Tue, 03 Mar 2026   Deviance:                       2463.3
Time:                        22:12:51   Pearson chi2:                 2.42e+04
No. Iterations:                    28   Pseudo R-squ. (CS):             0.9584
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -2.3925      0.186    -12.883      0.000      -2.756      -2.028
C(post_type)[T.GraphSidecar]    -0.8230      0.062    -13.256      0.000      -0.945      -0.701
C(business_type)[T.B2C]         -1.1937      0.069    -17.333      0.000      -1.329      -1.059
log_followers                    0.9156      0.013     70.063      0.000       0.890       0.941
age_days                         0.0006   5.95e-05     10.818      0.000       0.001       0.001
================================================================================================

/Users/pouriakhansari/anaconda3/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [9]:
model = smf.glm(
    'likes ~ media_count + I(media_count**2) + business_type + log_followers + age_days ',
    data=df_m,
    family=sm.families.NegativeBinomial()
).fit()


print(model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:                  likes   No. Observations:                 1316
Model:                            GLM   Df Residuals:                     1310
Model Family:        NegativeBinomial   Df Model:                            5
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -12942.
Date:                Tue, 03 Mar 2026   Deviance:                       2481.8
Time:                        22:13:35   Pearson chi2:                 2.74e+04
No. Iterations:                    38   Pseudo R-squ. (CS):             0.9578
Covariance Type:            nonrobust
========================================================================================
                           coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept               -2.1894      0.185    -11.811      0.000      -2.553      -1.826
business_type[T.B2C]    -1.1980      0.069    -17.444      0.000      -1.333      -1.063
media_count             -0.2541      0.023    -10.932      0.000      -0.300      -0.209
I(media_count ** 2)      0.0126      0.002      7.052      0.000       0.009       0.016
log_followers            0.9130      0.013     70.220      0.000       0.887       0.938
age_days                 0.0007   5.96e-05     11.518      0.000       0.001       0.001
========================================================================================

/Users/pouriakhansari/anaconda3/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [10]:
model = smf.glm(
    'comments ~ C(post_type) + business_type + log_followers + age_days ',
    data=df_m,
    family=sm.families.NegativeBinomial()
).fit()


print(model.summary())

                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               comments   No. Observations:                 1316
Model:                            GLM   Df Residuals:                     1311
Model Family:        NegativeBinomial   Df Model:                            4
Link Function:                    Log   Scale:                          1.0000
Method:                          IRLS   Log-Likelihood:                -7139.7
Date:                Tue, 03 Mar 2026   Deviance:                       3563.4
Time:                        22:14:14   Pearson chi2:                 1.69e+04
No. Iterations:                    24   Pseudo R-squ. (CS):             0.9266
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -8.5510      0.194    -44.167      0.000      -8.930      -8.172
C(post_type)[T.GraphSidecar]    -0.1063      0.065     -1.643      0.100      -0.233       0.021
business_type[T.B2C]            -1.8192      0.071    -25.787      0.000      -1.957      -1.681
log_followers                    1.0119      0.014     73.914      0.000       0.985       1.039
age_days                        -0.0004   6.09e-05     -7.258      0.000      -0.001      -0.000
================================================================================================

/Users/pouriakhansari/anaconda3/lib/python3.11/site-packages/statsmodels/genmod/families/family.py:1367: ValueWarning: Negative binomial dispersion parameter alpha not set. Using default value alpha=1.0.
  warnings.warn("Negative binomial dispersion parameter alpha not "

In [12]:

model = smf.ols(
    'comments ~ C(post_type) + business_type  + log_followers + age_days',
    data=df_m
).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:               comments   R-squared:                       0.188
Model:                            OLS   Adj. R-squared:                  0.186
Method:                 Least Squares   F-statistic:                     75.91
Date:                Tue, 03 Mar 2026   Prob (F-statistic):           6.17e-58
Time:                        22:15:44   Log-Likelihood:                -10419.
No. Observations:                1316   AIC:                         2.085e+04
Df Residuals:                    1311   BIC:                         2.087e+04
Df Model:                           4
Covariance Type:            nonrobust
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                    -1710.5663    123.446    -13.857      0.000   -1952.739   -1468.394
C(post_type)[T.GraphSidecar]   -15.7070     41.272     -0.381      0.704     -96.673      65.259
business_type[T.B2C]            60.9477     45.789      1.331      0.183     -28.880     150.775
log_followers                  137.0690      8.686     15.780      0.000     120.029     154.109
age_days                        -0.1362      0.040     -3.446      0.001      -0.214      -0.059
==============================================================================
Omnibus:                     2149.070   Durbin-Watson:                   1.267
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          1170576.739
Skew:                          10.376   Prob(JB):                         0.00
Kurtosis:                     147.628   Cond. No.                     4.19e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.19e+03. This might indicate that there are
strong multicollinearity or other numerical problems.

In [ ]:
print(df_regression)